import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Map, 
  CheckCircle2, 
  Clock, 
  ExternalLink, 
  Sparkles, 
  BookOpen, 
  Code2, 
  Layers, 
  ArrowRight, 
  Plus, 
  TrendingUp, 
  Award,
  Zap
} from 'lucide-react';
import { soundFx } from '../utils/audio';
import { RoadmapSprint, TalentProfile } from '../types';
import { AppRoute } from './AppLayout';

interface LearningRoadmapViewProps {
  roadmaps: RoadmapSprint[];
  currentProfile: TalentProfile;
  onToggleTask: (sprintId: string, taskId: string) => void;
  onNavigate: (route: AppRoute) => void;
}

export const LearningRoadmapView: React.FC<LearningRoadmapViewProps> = ({
  roadmaps,
  currentProfile,
  onToggleTask,
  onNavigate
}) => {
  const allTasks = roadmaps.flatMap(s => s.tasks);
  const completedTasks = allTasks.filter(t => t.completed);
  const completionPercentage = Math.round((completedTasks.length / allTasks.length) * 100) || 0;
  const remainingHours = allTasks.filter(t => !t.completed).reduce((sum, t) => sum + t.estimatedHours, 0);

  return (
    <div className="max-w-7xl mx-auto space-y-8">
      {/* Header Banner */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2.5 mb-1">
            <span className="p-1.5 rounded-lg bg-violet-500/10 text-violet-400">
              <Map className="w-5 h-5" />
            </span>
            <h2 className="text-2xl font-extrabold text-white tracking-tight">
              Personalized Learning Roadmap
            </h2>
          </div>
          <p className="text-xs sm:text-sm text-slate-400">
            Targeted weekly sprints generated by AI to bridge missing skill gaps for your desired frontier roles.
          </p>
        </div>

        {/* Progress Tracker Widget */}
        <motion.div
          whileHover={{ scale: 1.02 }}
          className="flex items-center gap-4 p-4 rounded-2xl glass-panel border border-violet-500/30 self-start md:self-auto text-xs"
        >
          <div>
            <div className="text-slate-400 text-[11px] font-medium">Roadmap Progress</div>
            <div className="text-lg font-extrabold text-white font-mono">{completionPercentage}% Completed</div>
          </div>
          <div className="w-24 h-2 bg-slate-900 rounded-full overflow-hidden">
            <div
              className="h-full bg-gradient-to-r from-violet-500 to-sky-400 rounded-full transition-all duration-500"
              style={{ width: `${completionPercentage}%` }}
            />
          </div>
          <div className="text-right pl-3 border-l border-white/10">
            <div className="text-slate-400 text-[11px] font-medium">Time to Target</div>
            <div className="text-sky-400 font-bold font-mono">~{remainingHours} hrs</div>
          </div>
        </motion.div>
      </div>

      {/* Sprints List */}
      <div className="space-y-6">
        {roadmaps.map((sprint) => {
          const sprintTasks = sprint.tasks;
          const sprintCompleted = sprintTasks.filter(t => t.completed).length;
          const sprintPercent = Math.round((sprintCompleted / sprintTasks.length) * 100) || 0;

          return (
            <motion.div
              key={sprint.id}
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              className="p-6 sm:p-8 rounded-2xl glass-panel border border-white/[0.08] space-y-6"
            >
              {/* Sprint Header */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-white/[0.08]">
                <div>
                  <div className="flex items-center gap-2.5 mb-1">
                    <span className="px-2.5 py-0.5 text-xs font-bold rounded-full bg-violet-500/15 text-violet-300 border border-violet-500/30 font-mono">
                      Sprint {sprint.sprintNumber}
                    </span>
                    <h3 className="text-base sm:text-lg font-bold text-white">
                      {sprint.title}
                    </h3>
                  </div>
                  <p className="text-xs text-sky-400 font-medium">
                    Target Alignment: {sprint.targetOpportunityTitle || 'Frontier Full-Stack Roles'}
                  </p>
                </div>

                <div className="flex items-center gap-3 text-xs">
                  <span className="text-slate-400">{sprintCompleted} of {sprintTasks.length} Completed</span>
                  <div className="w-20 h-2 bg-slate-900 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-emerald-400 rounded-full transition-all duration-300"
                      style={{ width: `${sprintPercent}%` }}
                    />
                  </div>
                </div>
              </div>

              {/* Task Items */}
              <div className="space-y-3">
                {sprint.tasks.map((task) => (
                  <motion.div
                    key={task.id}
                    whileHover={{ scale: 1.01 }}
                    className={`p-4 sm:p-5 rounded-2xl border transition-all ${
                      task.completed
                        ? 'bg-emerald-500/[0.03] border-emerald-500/25'
                        : 'bg-slate-950/80 border-white/[0.08] hover:border-violet-400/40'
                    }`}
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex items-start gap-3.5 flex-1">
                        <button
                          onClick={() => {
                            soundFx.playSwitch();
                            onToggleTask(sprint.id, task.id);
                          }}
                          className={`mt-0.5 w-5 h-5 rounded-lg border flex items-center justify-center transition-all cursor-pointer ${
                            task.completed
                              ? 'bg-emerald-500 border-emerald-400 text-slate-950 shadow-sm'
                              : 'bg-slate-900 border-white/20 hover:border-violet-400 text-transparent'
                          }`}
                        >
                          <CheckCircle2 className="w-3.5 h-3.5" />
                        </button>

                        <div className="space-y-1.5 flex-1">
                          <div className="flex flex-wrap items-center gap-2">
                            <h4 className={`text-sm sm:text-base font-bold ${task.completed ? 'line-through text-slate-400' : 'text-white'}`}>
                              {task.title}
                            </h4>
                            <span className="text-xs px-2.5 py-0.5 rounded-full bg-violet-500/10 text-violet-300 border border-violet-500/20 font-medium">
                              {task.skillTag}
                            </span>
                            <span className="text-xs px-2 py-0.5 rounded-full bg-white/[0.04] text-slate-400">
                              {task.difficulty}
                            </span>
                          </div>

                          <p className="text-xs text-slate-300 leading-relaxed">
                            {task.description}
                          </p>

                          {/* Curated Resource Link */}
                          {task.resourceTitle && (
                            <div className="pt-2 flex items-center gap-2 text-xs">
                              <span className="px-2 py-0.5 rounded bg-white/[0.04] text-slate-400 text-[11px]">
                                {task.resourceType}
                              </span>
                              <a
                                href={task.resourceLink || '#'}
                                target="_blank"
                                rel="noreferrer"
                                className="text-sky-400 hover:text-sky-300 font-semibold flex items-center gap-1 truncate"
                              >
                                <BookOpen className="w-3.5 h-3.5 shrink-0" />
                                <span className="truncate">{task.resourceTitle}</span>
                                <ExternalLink className="w-3 h-3 shrink-0" />
                              </a>
                            </div>
                          )}
                        </div>
                      </div>

                      <div className="text-right text-xs text-slate-400 shrink-0 flex items-center gap-1 font-mono">
                        <Clock className="w-3.5 h-3.5 text-slate-500" />
                        <span>~{task.estimatedHours}h</span>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.div>
          );
        })}
      </div>

      {/* Capstone Challenge Prompt */}
      <div className="p-6 sm:p-8 rounded-2xl glass-panel border border-sky-400/20 bg-gradient-to-br from-sky-500/[0.03] to-indigo-500/[0.03] space-y-4">
        <div className="flex items-center gap-2.5">
          <Award className="w-5 h-5 text-sky-400" />
          <h3 className="text-base font-bold text-white">Recommended Capstone Project Prompt</h3>
        </div>
        <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
          <strong>Project Architecture:</strong> Build an in-browser WebContainer REPL that streams executed code outputs using WebSockets and Yjs CRDTs. 
          Completing this repository will satisfy 100% of missing skill requirements across Anthropic, Linear, and Vercel roles.
        </p>
        <div className="flex flex-wrap items-center gap-3 pt-2">
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={() => {
              soundFx.playBlip(1000);
              onNavigate('copilot');
            }}
            className="px-4 py-2.5 rounded-xl bg-sky-500/15 hover:bg-sky-500/25 border border-sky-400/30 text-sky-300 text-xs font-semibold flex items-center gap-2 transition-colors cursor-pointer"
          >
            <span>Ask Career Copilot to Scaffold Architecture</span>
            <ArrowRight className="w-4 h-4" />
          </motion.button>
        </div>
      </div>
    </div>
  );
};
